// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.21.12
// source: proto/mailing.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty } from "../google/protobuf/empty";

export const protobufPackage = "mailing";

export interface SendCodeRequest {
  to: string;
  code: string;
  companyName: string;
  logoUrl: string;
}

export const MAILING_PACKAGE_NAME = "mailing";

export interface MailingServiceClient {
  sendCode(request: SendCodeRequest): Observable<Empty>;
}

export interface MailingServiceController {
  sendCode(request: SendCodeRequest): void;
}

export function MailingServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["sendCode"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("MailingService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("MailingService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MAILING_SERVICE_NAME = "MailingService";
